---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =  {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/defiler/defiler-run.png",
            width = 297,
            height = 309,
            frame_count = 8,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/defiler/defiler-death.png",
            width = 299,
            height = 311,
            frame_count = 4,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.375,
            animation_speed = 0.2
        }
    }
}