---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-run.png",
            width = 376,
            height = 352,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 1,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    attack = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-construction.png",
            width = 706,
            height = 756,
            frame_count = 7,
            axially_symmetrical = false,
            direction_count = 1,
            scale = 0.4,
            animation_speed = 0.2,
            repeat_count = 12,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    corpse = {
        filename = "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-death.png",
        width = 525,
        height = 536,
        frame_count = 7,
        direction_count = 1,
        axially_symmetrical = false,
        scale = 0.4,
        animation_speed = 0.2
    }
}