---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/guardian/guardian-run.png",
            width = 377,
            height = 317,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 4, 0 }
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/guardian/guardian-death.png",
            width = 552,
            height = 658,
            frame_count = 8,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.375,
            animation_speed = 0.5
        }
    }
}