---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =                  {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-run.png",
            width = 257,
            height = 268,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    attack = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-attack.png",
            width = 258,
            height = 300,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.5
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-death.png",
            width = 549,
            height = 528,
            frame_count = 8,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.4,
            animation_speed = 0.2
        }
    }
}