---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-attack.png",
            width = 258,
            height = 300,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.5
        },
        shadow = {
            shift = { 4, 0 }
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/mutalisk/mutalisk-death.png",
            width = 346,
            height = 344,
            frame_count = 7,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.4,
            animation_speed = 0.2
        }
    }
}