---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/parasite/parasite-run.png",
            width = 89,
            height = 81,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.48,
            animation_speed = 0.6
        },
        shadow = {
            shift = { 4, 0 }
        },
        team = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/parasite/parasite-run_teamcolour.png",
            width = 89,
            height = 81,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.48,
            animation_speed = 0.6
        },
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/parasite/parasite-death.png",
            width = 682,
            height = 594,
            frame_count = 12,
            axially_symmetrical = false,
            direction_count = 1,
            scale = 0.48,
            animation_speed = 0.6
        }
    }
}