---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =  {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-run.png",
            width = 426,
            height = 387,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.54,
            animation_speed = 0.2,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    attack = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-attack.png",
            width = 451,
            height = 453,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.54,
            animation_speed = 0.2
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-death.png",
            width = 542,
            height = 564,
            frame_count = 11,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.54,
            animation_speed = 0.1
        }
    }
}