---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:38 PM
---

return {
    run = {
        main =              {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/sunken_colony/sunken_colony.png",
            width = 521,
            height = 503,
            frame_count = 3,
            direction_count = 1,
            scale = 0.5,
            run_mode = "forward-then-backward",
        },
        shadow = {
            shift = {0.2, 0}
        }
    },
    attack = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/sunken_colony/sunken_colony_attack.png",
            width = 521,
            height = 503,
            frame_count = 11,
            direction_count = 3,
            scale = 0.5,
            run_mode = "forward-then-backward",
        }
    }
}